### PR TITLE
Redo overloads and delete my sanity

### PR DESCRIPTION
**Pull request by Perksey**
# Summary of the PR
why am i doing this to myself again

# Related issues, Discord discussions, or proposals
Links go here.

# Further Comments

### CODE REVIEW

**Comment by Perksey** [comment]
# Progress
## Early
- [x] String
- [x] Group

## Prompt
- [ ] Span & Ref

## Late
- [ ] IntPtr
- [ ] ArrayParameter
- [ ] ReturnType
- [ ] StringArray

## Scrapped
- Flow Pointer (replaced with ref)
- String return (handled in the string early overloader)
- Pointer parameter (replaced with span & ref)
- Pointer return value (scrapped entirely)

**Comment by Perksey** [comment]
This is ready for review, but it's probably best we review the bindings rather than the binder as we've been operating under the `as long as it works idgaf what it looks like` code style for the binder.

@frederikja163 seeing as you're the main driving force behind this change, can you be responsible for testing the usefulness of this new overload system?

**Comment by frederikja163** [comment]
I can take it for a test drive sure, you send me the nuget packages over and i will give it a shot on the tutorials

**Comment by Perksey** [comment]
Will do, just need to fix the group overloads which seemingly still don’t work

**Comment by frederikja163** [comment]
Good job!

**Pull request merged**
