### PR TITLE
Add VS Code support for tutorials

### PR DESCRIPTION
**Pull request by moozzyk**
# Summary of the PR

Fixes: #273

Adding tasks and launch configurations to allow running and debugging
tutorial projects directly from Visual Studio Code.
Newly added tasks also allow publishing tutorial projects and running
them under under the wather.

Verification:
- Ran each added launch configuration from VS Code
- Published a couple projects and made sure artificats were written to
  the expected location
- Ran a couple projects under the watcher

image

image

### CODE REVIEW

**Comment by Perksey** [comment]
Please see the latest discussion on the issue. We're only interested in a `launchsettings.json` file which is standard across most C# IDEs. I'm not sure what the level of support of this is in VSCode, however we don't want IDE-specific files in the repository.

**Comment by moozzyk** [comment]
My understanding is that `launchSettings.json` is used by ASP.Net Core and the tutorial projects are not ASP.Net projects. As such I don't think it is possible to add `launchSettings.json` to these projects that would work in any C# IDE. As a side note, `launchSettings.json` is also not supported by VS Code - see the comment in the vs code repo https://github.com/microsoft/vscode/issues/71007#issuecomment-475921297.

**Comment by Perksey** [comment]
Ah ok, I didn't know that. Seeing as the .vscode directory is seemingly used by all Monarch-based editors such as VS Code and GitHub Codespaces for example, I think I'm finally just gonna give in and let this slide unless @HurricanKai has any objections.

**Comment by HurricanKai** [comment]
I'm good with this. I would still like to have a launchSettings.json file in the future though.

**Review by Perksey — APPROVED** [review]
Good for merge once the CLA has been signed.

**Comment by moozzyk** [comment]
I am working on approval to sign CLA.

**Comment by Perksey** [comment]
Any update on the CLA front? As long as you didn't make this PR during paid hours or as part of your usual working duties, you shouldn't need approval from your employer.

**Comment by moozzyk** [comment]
Still waiting for approval. It's outside my control - last time it took about two weeks.

**Comment by moozzyk** [comment]
I signed the CLA.

**Pull request merged**
