### PR TITLE
Implement cursor modes

### LINKED ISSUE #124: Cursor mode is not fully implemented :/
# Summary of feature
Cursor mode enum is there but it is not used yet nor is it changeable.

# Comments
Basically I forgot to add this functionality in my previous PR. Shame on me. :( This has still to be implemented. Shouldn't be much of work hopefully.

### PR DESCRIPTION
**Pull request by Pyrdacor**
# Summary of the PR
Extend ICursor interface to make cursor mode changeable. Implement cursor mode behavior for GLFWCursor.

# Related issues, Discord discussions, or proposals
Fixes #124

### CODE REVIEW

**Comment by Pyrdacor** [comment]
I have to add a call to `Glfw.GetInputMode` to retrieve raw mouse motion flag. The return value is bool in that case but there is already a version of `GetInputMode` with the same parameters which returns `CursorModeValue`. As C# doesn't support return type covariance how can I implement this with SuperInvoke?

My guess would be returning just `object` or use a generic version like `T GetInputMode<T>(...)` but I don't know how SuperInvoke works in that case. Would prefer the generic version if this is possible.

**Comment by Perksey** [comment]
Just add a GLFW-specific struct in the Silk.NET.GLFW package and convert it to the Silk.NET.Input.Common struct after

**Comment by Pyrdacor** [comment]
Hm I noticed that the return type in glfw is just int which is interpreted as bool (0 or 1) or as the enums int value in the other case. Maybe I just change it to int and convert it when I call it.

**Comment by Perksey** [comment]
I’m not sure how good SuperInvokes marshalling with stuff like out bool is but if it’s just a normal bool SuperInvoke will automatically Marshall it to 0 or 1

**Comment by Pyrdacor** [comment]
Should work as expected now. Can be merged I guess.

**Pull request merged**
