### PR TITLE
Minify Trees

### LINKED ISSUE #298: Name minification
Minify generated names. Should decrease IL size somewhat.

### PR DESCRIPTION
**Pull request by HurricanKai**
Resolves #298

### CODE REVIEW

**Comment by Perksey** [comment]
Have you ensured that the Lab applications still work.

**Comment by HurricanKai** [comment]
Not all of them, but I have done a bit of testing - it's also very unlikely that this will break anything, as it only affects private members.

**Comment by Perksey** [comment]
Fair enough. As long as the Triangle works, I'm happy to merge.

**Comment by HurricanKai** [comment]
image

**Review by Perksey — APPROVED** [review]

**Pull request merged**
