### PR TITLE
Add click events

### LINKED ISSUE #78: Add built-in support for click/doubleclick
The input layer only has mouse up and down events. Double clicks are a very common use case. At the moment every Silk user is forced to implement this functionality on its own. A general built-in support is much appreciated.

Adding events for Click and DoubleClick would be nice.

### PR DESCRIPTION
**Pull request by Pyrdacor**
# Summary of the PR
Add events for single click and double click.

# Related issues, Discord discussions, or proposals
Closes #78

### CODE REVIEW

**Comment by Pyrdacor** [comment]
I didn't test anything and there is a TODO comment cause I don't know how to handle the case yet. So this is still WIP. :D

**Comment by Pyrdacor** [comment]
@Perksey I can't build the current master on Ubuntu 19.04. He complains about missing references. Hundreds of lines like this:

Interfaces/IAtiVertexStreams.gen.cs(673,10): error CS0246: The type or namespace name 'NativeSymbolAttribute' could not be found (are you missing a using directive or an assembly reference?) [/home/pyrdacor/projects/Misc/Silk.NET/src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ATI/Silk.NET.OpenGL.Legacy.Extensions.ATI.csproj]
Interfaces/IAtiVertexStreams.gen.cs(673,10): error CS0246: The type or namespace name 'NativeSymbol' could not be found (are you missing a using directive or an assembly reference?) [/home/pyrdacor/projects/Misc/Silk.NET/src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ATI/Silk.NET.OpenGL.Legacy.Extensions.ATI.csproj]

I ran `generator.sh` and then `dotnet build Silk.NET.sln`. Am I missing something?

**Comment by Perksey** [comment]
You'll need to delete the Interfaces, Structs, and Enums folder due to the changes made when moving away from ADL to SuperInvoke. It's probably best to commit your changes to some branch somewhere and then clone the repo anew.

**Comment by Pyrdacor** [comment]
Ok thanks. The following did the trick. :D

    rm -r src
    git reset --hard

**Comment by Pyrdacor** [comment]
Ok I tested it with the Triangle example and it seems to work. Maybe someone could check again. I used:
```cs
           var mouse = _window.CreateInput().Mice.First();
            mouse.Click += (mouse, button) => {
                Console.WriteLine("Single click with button: " + button.ToString());
            };
            mouse.DoubleClick += (mouse, button) => {
                Console.WriteLine("Double click with button: " + button.ToString());
            };
```

**Comment by Pyrdacor** [comment]
@Perksey @devvoid I think it's ready for merge now.

**Comment by Perksey** [comment]
Could you add this to the InputTest program in the lab please so we can test this again in the future? Once this is done I'll have a go at testing it on my end.

**Comment by Pyrdacor** [comment]
@Perksey Done. Yeah double click logic is much harder than it looks on first glance. I read a few articles about it and there is not even a general approach for this. Some people use timers but my solution luckily doesn't even need timers or events which would possibly introduce parallel executions. It's all handled nicely by the update routine. :)

**Comment by Pyrdacor** [comment]
@Perksey I re-checked my code. There might be a problem with multi-threaded update logic though as the Update event won't be tied to the same thread as the glfw event raising. I might be wrong but maybe we should consider that. It is a bit sad because it will make the logic much more complicated. :/

**Comment by Pyrdacor** [comment]
I wonder if we could add an internal update event which is not affected by the "single threaded" option and which is only used for input etc. Because we don't want asynchronous input updates/events at all.

**Comment by Perksey** [comment]
Should be a non-issue, glfwPollEvents is always ran on the main thread with the main game loop, which then calls the events bound within Silk.

**Comment by Perksey** [comment]
I’ll have a play when I get home.

**Comment by Pyrdacor** [comment]
The problem is the following code inside GlfwInputContext.cs:

```cs
window.Update += _update = _ =>
{
	foreach (var updatable in _mice
	{
		updatable.Update();
	}

	foreach (var updatable in _gamepads)
	{
		updatable.Update();
	}
                
	foreach (var updatable in _joysticks)
	{
		updatable.Update();
	}
};
```

`window.Update` is raised by a Task in multi-threaded mode. Therefore the Update methods are also called within the Task and this isn't what we want at all I guess.

So I thought about adding an `InternalUpdate` or `SingleThreadedUpdate` only to `GlfwWindow` (not to the interface) which is used in the above code instead.

GlfwWindow will then raise the internal event on the main thread in any case. As an end-user will not even see this event through the interface it is no big deal imho.

```cs
public void DoUpdate()
{
	RaiseInternalUpdate(); // this is new and specific for GlfwWindow

	if (UseSingleThreadedWindow)
	{
		RaiseUpdateFrame();
	}
	else
	{
		// Raise UpdateFrame, but don't await it yet.
		var task = Task.Run(RaiseUpdateFrame); // cast to action, ambiguous call

		// Loop while we're still updating - the Update thread might be calling the main thread
		while (!task.IsCompleted)
		{
			if (!_invokeQueue.IsEmpty && _invokeQueue.TryDequeue(out var invokeCall))
			{
				invokeCall.GetAwaiter().GetResult();
			}
		}
	}
}
```

**Comment by Pyrdacor** [comment]
Another option would be to provide a MainThreadUpdate in any case for the end-user (which we could use for input then as well). So an end-user could decide to run code on the main thread or on another thread in multi-threaded mode. But I'm not sure if this is useful.

**Comment by Perksey** [comment]
if (window.SingleThreaded)
    update as normal
else
    use window.Invoke

**Comment by Pyrdacor** [comment]
@Perksey Hopefully I understood you right. See my last commit.

**Comment by Pyrdacor** [comment]
Is the Invoke logic broken? I am not really understanding it but when I replace the `new Task<object>...` part in `GlfwWindow.Invoke` with `var task = Task.Run(() => d.DynamicInvoke(args));` it is working. Otherwise a call to `Invoke` from within the `Update` event will cause a deadlock.

**Comment by Perksey** [comment]
The task can’t be started immediately, which is what Task.Run does. Instead what we do is register the delegate as a task and await it later on.

**Comment by Pyrdacor** [comment]
I understand but it seems that it never is started at all. Does `invokeCall.GetAwaiter().GetResult();` even start the task?

**Comment by Pyrdacor** [comment]
Wouldn't `RunSynchronously` be the right choice here?

**Comment by Perksey** [comment]
GetAwaiter().GetResult() is the most common way to synchronously wait for a task to complete. I don’t think changing the invoke system is within the scope for this PR.

**Comment by Pyrdacor** [comment]
I agree but my problem now is that the current invoke logic leads to a deadlock for multi-threaded windows (e.g. the input test project).

But if I understand it correctly, the multi-threaded logic will still assure that the Update event is triggered between two `DoEvents` calls. Am I right? If so we won't need the last commit of this PR at all.

**Comment by Perksey** [comment]
Currently 
- the update event is called in another thread 
- on the main thread, we start waiting and executing incoming invocations until the invocation is complete

**Comment by Pyrdacor** [comment]
Ok so the main loop waits till the update event is finished before it starts again. This is all that's important.

**Comment by Pyrdacor** [comment]
Ok I force pushed to omit the last commit with the unneccessary invoke logic. Test project was extended as said before. So merge and test to your liking. :)

**Comment by Perksey** [comment]
Tested my end, works. Approved to merge.

**Comment by Pyrdacor** [comment]
Yeah we could change the default values a bit. I guess 500ms is default on windows but it seems very high.

In general it is best to set it to the OS setting but this must be handled by the API user.

**Pull request merged**
