### PR TITLE
C# 8 Support

### PR DESCRIPTION
**Pull request by HurricanKai**
# Summary of the PR
Adds Usage Features C# 8 Adds, nullable reference types, readonly members, advanced Patterns, `Index`, `Range` where Applicable. (I don't know the Code base, so we will see how much needs to change) 

# Related issues, Discord discussions, or proposals
#39 

# Further Comments
I'll try to keep Commits using different new features separated, in case there's a decision to not use specific ones.

### CODE REVIEW

**Comment by HurricanKai** [comment]
Last Commit Nicely Demonstrates how I plan to do this everywhere. Resolving any Warnings, and removing any referencing `[NotNull]` `[ItemNotNull]` etc. Attributes

**Comment by HurricanKai** [comment]
Opened #41, this PR would greatly benefit & will need a revisit when (if) #41 is resolved.

**Comment by Perksey** [comment]
Looking to get this merged as we have some breaking changes to do. Can you fix the build errors on the CI and then I'll merge it, complete or not.

We need to do a massive refactor to support Vulkan.

**Comment by HurricanKai** [comment]
no local changes. merge when needed

**Pull request closed without merging**
