### PR TITLE
Fix `Get` methods

### PR DESCRIPTION
**Pull request by johnkellyoxford**
# Summary of the PR
Fix the get methods to a) work properly and b) work nicely

# Further Comments
These methods in themselves are abominations, and just a weird rewrite of indexing (`Get(p, 11)` is exactly equivalent to `p[11]`). Seems logical to remove them if not part of current public API

### CODE REVIEW

**Comment by johnkellyoxford** [comment]
Entirely removed the get methods given they are only used twice

**Comment by Perksey** [comment]
I think we've already done this on the glfw-input branch actually on one of the more recent commits

**Comment by johnkellyoxford** [comment]
I pulled the glfw-input branch and edited it on that

**Comment by Perksey** [comment]
Ah ok, I thought I got them all! Will double check this and then merge it in. :)

**Pull request merged**
