### PR TITLE
Language Version 9.0

### PR DESCRIPTION
**Pull request by HurricanKai**
C# 9 is go live now.
This PR replaces all preview usages with 9.0 which should now be equivalent.

### CODE REVIEW

**Review by Perksey — APPROVED** [review]

**Comment by Perksey** [comment]
Please resolve conflicts before merge.

**Comment by HurricanKai** [comment]
Trying to figure out why the build is failing. Updating to RC2 seems to have helped somewhat 🤔

**Comment by Perksey** [comment]
For some reason it's convinced that windowing.common doesn't reference core.

**Comment by HurricanKai** [comment]
I have zero clue what's going on with the CI, but I've removed all generator changes to prevent merge issues

**Pull request merged**
