### PR TITLE
Potential extension system for windowing?

### PR DESCRIPTION
**Pull request by Perksey**
# Summary of the PR
So I was just about to start work on SDL stuff when I thought of what could be a pretty neat extension mechanism for windowing. What do you guys think?

# Related issues, Discord discussions, or proposals
Links go here.

# Further Comments

### CODE REVIEW

**Comment by HurricanKai** [comment]
I think that's just something interfaces could do, what's the advantage?

**Comment by Deecellar** [comment]
Exactly in what mechanism would extension work, cost and stuff

**Comment by Perksey** [comment]
Essentially the idea is you can specify extra config which the windowing system takes into account when creating a window. It's main use case is for backend-specific functionaliy that we don't expose via the windowing backend directly, such as manual specification of window hints.

In the current form of the windowing system, there's no way to know for sure what backend a window is created with (apart from in 1.0 where glfw is the only windowing backend) so you can specify backend-specific config which is applied if supported, but discarded if not.

**Comment by HurricanKai** [comment]
that can easily be produced by using a combination of Interfaces and the ctor, without bloating the `IView` interface with useless, unsafe functions.

**Comment by Perksey** [comment]
Closing this PR due to indecision and will hold off on introducing any kind of extension mechanism into windowing

**Pull request closed without merging**
